#!/usr/bin/env python
# coding: utf-8

# In[4]:


import os
import mlflow
import shutil
from parallels_plugin import parallels_files_meta

import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--input_data_spec', type=str, required=True)
args = parser.parse_args()
ids = parallels_files_meta.input_data_spec_to_json(args.input_data_spec)
print('Input Data Spec=' + str(ids))

# In[5]:


df = parallels_files_meta.list_files_meta('jaganes-pythonlambda-test', 'etc', input_name='in1')


# In[ ]:


print(df.to_string())


# In[6]:


file_list = parallels_files_meta.get_file_paths_local(df)
print(file_list)


# In[ ]:


df = df[df.apply(lambda row: '.infinstor' not in row['FileName'], axis=1)]
file_list = parallels_files_meta.get_file_paths_local(df)
print(file_list)


# In[ ]:


print(df.to_string())


# In[7]:


outdir = "/tmp/output2/"
os.mkdir(outdir)
for f in file_list:
    shutil.copy(f, outdir)


# In[8]:


parallels_files_meta.infin_log_artifacts(outdir, "output")


